version: "3"

networks:
  etcd_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_CONFIG_SUBNET}

services:
  etcd-0:
    networks:
      etcd_net:
        ipv4_address: 172.16.238.11
    image: quay.io/coreos/etcd:v3.4.14-ppc64le
    ports:
      - 172.16.238.11:4001:4001
      - 172.16.238.11:2380:2380
      - 172.16.238.11:2379:2379
    hostname: etcd-0
    environment:
      - GOMAXPROCS=2
    command: >-
      /usr/local/bin/etcd
      -name etcd-0
      -advertise-client-urls http://etcd-0:2379,http://etcd-0:4001
      -listen-client-urls http://172.16.238.11:2379,http://172.16.238.11:4001
      -initial-advertise-peer-urls http://etcd-0:2380
      -listen-peer-urls http://172.16.238.11:2380
      -initial-cluster-token etcd-cluster
      -initial-cluster etcd-0=http://etcd-0:2380,etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380
      -initial-cluster-state new
      -debug
  etcd-1:
    networks:
      etcd_net:
        ipv4_address: 172.16.238.12
    image: quay.io/coreos/etcd:v3.4.14-ppc64le
    ports:
      - 172.16.238.12:4001:4001
      - 172.16.238.12:2380:2380
      - 172.16.238.12:2379:2379
    hostname: etcd-1
    environment:
      - GOMAXPROCS=2
    command: >-
      /usr/local/bin/etcd
      -name etcd-1
      -advertise-client-urls http://etcd-1:2379,http://etcd-1:4001
      -listen-client-urls http://172.16.238.12:2379,http://172.16.238.12:4001
      -initial-advertise-peer-urls http://etcd-1:2380
      -listen-peer-urls http://172.16.238.12:2380
      -initial-cluster-token etcd-cluster
      -initial-cluster etcd-0=http://etcd-0:2380,etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380
      -initial-cluster-state new
      -debug
  etcd-2:
    networks:
      etcd_net:
        ipv4_address: 172.16.238.13
    image: quay.io/coreos/etcd:v3.4.14-ppc64le
    ports:
      - 172.16.238.13:4001:4001
      - 172.16.238.13:2380:2380
      - 172.16.238.13:2379:2379
    hostname: etcd-2
    environment:
      - GOMAXPROCS=2
    command: >-
      /usr/local/bin/etcd
      -name etcd-2
      -advertise-client-urls http://etcd-2:2379,http://etcd-2:4001
      -listen-client-urls http://172.16.238.13:2379,http://172.16.238.13:4001
      -initial-advertise-peer-urls http://etcd-2:2380
      -listen-peer-urls http://172.16.238.13:2380
      -initial-cluster-token etcd-cluster
      -initial-cluster etcd-0=http://etcd-0:2380,etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380
      -initial-cluster-state new
      -debug
